modLoader = "javafml"
loaderVersion = "[39,)"
issueTrackerURL = "https://github.com/Surreality-Modding/${repo}/issues"
license = "GPLv3"

[[mods]]
modId = "outstretch"
version = "${version}"
displayName = "${name}"
authors = "Surreality Modding"
credits = "Haunted Chest, StevenPlayzz, Noodlescript, CircleF1sh"
description = "A new mod adding small additions to the game."
displayURL = "https://discord.io/surrealitymodding"
#updateJSONURL = ""
#logoFile = ""

[[dependencies.${id}]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "pollen"
mandatory = true
versionRange = "[1.0.0,)"
ordering = "BEFORE"
side = "BOTH"